mysql:
  enabled: false
  host: "localhost"
  port: "3306"
  database: "root@server"
  user: "root"
  password: "admin"

redis:
  enabled: false
  address: 0.0.0.0
  username: 'default'
  password: 'password'

#Types: REPORT_BUG, COMMUNITY_GUIDELINES, SUPPORT, STATUS, FEEDBACK, COMMUNITY, WEBSITE, FORUMS, NEWS, ANNOUNCEMENTS;
serverlinks:
  site:
    name: "&aSite do Servidor"
    url: "https://alliancecraft.net"
    type: NEWS