package net.joseplay.allianceutils.api.materialVariants;

import java.util.Arrays;

public enum VariantType {
    DIAMOND("DIAMOND"),
    EMERALD("EMERALD"),
    GOLD("GOLD"),
    IRON("IRON"),
    LAPIS("LAPIS"),
    NETHERITE("ANCIENT_DEBRIS"),
    REDSTONE("REDSTONE"),
    COPPER("COPPER"),
    COAL("COAL"),
    QUARTZ("QUARTZ"),
    OAK("OAK"),
    STRIPPED_OAK("STRIPPED_OAK"),
    BIRCH("BIRCH"),
    STRIPPED_BIRCH("STRIPPED_BIRCH"),
    SPRUCE("SPRUCE"),
    STRIPPED_SPRUCE("STRIPPED_SPRUCE"),
    JUNGLE("JUNGLE"),
    STRIPPED_JUNGLE("STRIPPED_JUNGLE"),
    ACACIA("ACACIA"),
    STRIPPED_ACACIA("STRIPPED_ACACIA"),
    DARK_OAK("DARK_OAK"),
    STRIPPED_DARK_OAK("STRIPPED_DARK_OAK"),
    MANGROVE("MANGROVE"),
    STRIPPED_MANGROVE("STRIPPED_MANGROVE"),
    CHERRY("CHERRY"),
    STRIPPED_CHERRY("STRIPPED_CHERRY"),
    CRIMSON("CRIMSON"),
    STRIPPED_CRIMSON("STRIPPED_CRIMSON"),
    WARPED("WARPED"),
    STRIPPED_WARPED("STRIPPED_WARPED"),
    SAND("SAND"),
    COBBLESTONE("COBBLESTONE"),
    CLAY("CLAY"),
    NETHERRACK("NETHERRACK"),
    CACTUS("CACTUS"),
    TERRACOTTA_WHITE("TERRACOTTA_WHITE"),
    TERRACOTTA_ORANGE("TERRACOTTA_ORANGE"),
    TERRACOTTA_MAGENTA("TERRACOTTA_MAGENTA"),
    TERRACOTTA_LIGHT_BLUE("TERRACOTTA_LIGHT_BLUE"),
    TERRACOTTA_YELLOW("TERRACOTTA_YELLOW"),
    TERRACOTTA_LIME("TERRACOTTA_LIME"),
    TERRACOTTA_PINK("TERRACOTTA_PINK"),
    TERRACOTTA_GRAY("TERRACOTTA_GRAY"),
    TERRACOTTA_LIGHT_GRAY("TERRACOTTA_LIGHT_GRAY"),
    TERRACOTTA_CYAN("TERRACOTTA_CYAN"),
    TERRACOTTA_PURPLE("TERRACOTTA_PURPLE"),
    TERRACOTTA_BLUE("TERRACOTTA_BLUE"),
    TERRACOTTA_BROWN("TERRACOTTA_BROWN"),
    TERRACOTTA_GREEN("TERRACOTTA_GREEN"),
    TERRACOTTA_RED("TERRACOTTA_RED"),
    TERRACOTTA_BLACK("TERRACOTTA_BLACK"),
    SIGN("SIGN"),
    WALL_SIGN("WALL_SIGN");

    private final String name;

    VariantType(String name) {
        this.name = name;
    }

    public static VariantType getFromName(String name){
        return Arrays.stream(values())
                .filter(v -> v.getName().equals(name))
                .findFirst()
                .orElse(null);
    }

    public String getName() {
        return name;
    }
}
